# main text of home
name: Eric W. Tramel, Ph.D.
bio: 'ML Research & Engineering'

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.jpg

# If you want to include your resume, set to true
# and specify source (external or local).
resume: false
resume-external: true
resume-url: https://google.com/?q=my+resume

url: http://eric-tramel.github.io

source: src
dest: _site

permalink: /:title/
# Conversion
markdown:    kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
  footnote_backlink: "&#x21A9;&#xFE0E;" 
  footnote_nr: 1
  hard_wrap : false
  toc_levels: 1..6

# To enable google analytics, supply your token below
analytics-google: 'UA-36574119-2'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, set to false
disqus: false

# if you don't have any of social below, comment the line
# facebook: myfacebook
twitter: fujikanaeda
googlescholar: jre2iwMAAAAJ
# instagram: myinstagram
# pinterest: mypinterest
linkedin: erictramel
# youtube: myyoutube
# spotify: myspotify
github: 'eric-tramel'
# medium: medium
email: eric.tramel@gmail.com
cv: /assets/doc/ewt-cv.pdf

authors:
    erictramel:
        name: Eric W. Tramel, Ph.D. 
        bio: Senior Machine Learning Scientist, Owkin
        external-image: false
        picture: assets/images/profile.jpg
        twitter: fujikanaeda

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
projects: false
# if you don't need "about" or "blog", comment them out below
about: true
blog: true
publications: true

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: false

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: true

plugins:
#  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin

jekyll-mentions:
    base_url: https://github.com

compress_html:
    ignore:
        envs:
        - development
        - stage

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, indigo-gh-pages.zip, Rakefile, screen-shot.png, travis.sh,indigo.sublime-project]


## Building Options


## Serving Options
port: 4000
host: localhost
baseurl: "" 
show_dir_listing: false
detach: false
livereload: true