# main text of home
name: Miquel Beltran
bio: Software engineer, Android specialist and newbie mentor

# twitter summary info
description: Miquel Beltran personal website

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.jpg

# If you want to include your resume, set to true
# and specify source (external or local).
resume: false
resume-external: true
resume-url: https://google.com/?q=my+resume

url: https://miquelbeltran.github.io
# your url: http://USERNAME.github.io

permalink: /:title/

# To enable google analytics, supply your token below
analytics-google: 'UA-569590-4'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, leave categories empty
disqus:
  shortname: mydisqus # enter this from your disqus account
  categories: [] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
#facebook: mi
twitter: miqubel
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
linkedin: miquelbeltran
# youtube: myyoutube
# spotify: myspotify
github: miquelbeltran
stackoverflow: 673294/mike
# quora: userquora
# reddit: username
medium: miqubel
# vimeo: myvimeo
email: miquelbeltran@gmail.com

authors:
    miquel:
        name: Miquel Beltran
        bio: Software engineer, Android specialist and newbie mentor
        external-image: false
        picture: assets/images/profile.jpg
        twitter: miqubel

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
projects: true

# if you don't need "about" or "blog", comment them out below
about: true
blog: true

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: false

gems:
  - jekyll-seo-tag
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com
