excerpt_separator: <!--more-->

# main text of home
title: www.jimmdenton.com
name: James Denton
bio: openstack, networking, and random musings.

# twitter summary info
description: A blog about cloud and networking and other related things

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.jpg

url: http://www.jimmdenton.com
permalink: /:title/

markdown: kramdown
highlighter: rouge

# To enable google analytics, supply your token below
analytics-google: 'UA-84784464-1'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, set to false
#disqus: mydisqus
disqus: false

# if you don't have any of social below, comment the line
#facebook: myfacebook
twitter: jimmdenton
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
linkedin: jamesmdenton
#youtube: myyoutube
#spotify: myspotify
github: busterswt
#medium: medium
#vimeo: myvimeo
email: james.denton@outlook.com

authors:
    jamesdenton:
        name: James Denton
        bio: openstack, networking, and random musings
        external-image: false
        picture: assets/images/profile.jpg
        twitter: jimmdenton

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# if you don't need pagination, comment the *paginate* configs below
#paginate: 5
#paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
projects: false

# if you don't need "about" or "blog", comment them out below
about: true
blog: true

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# show next & prev links in blog post?
blog-nav-links: false

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: true

sass:
    sass_dir: _sass
    style: :compressed

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com
