name: Phat Nguyen
bio: 'A magician who turns coffee into codes'
picture: 'assets/images/mybio.jpg'

url: http://npvinhphat.github.io
# your url: http://USERNAME.github.io
permalink: /:title/

markdown: kramdown
highlighter: rouge

analytics: 'UA-MYANALYTICS'
disqus: mydisqus
facebook: NPVPhat
twitter: npvinhphat
instagram:
linkedin:
youtube:
spotify:
github: npvinhphat
email: npvinhphat@gmail.com

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor]

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
projects: true

# if you don't need about or blog, comment them out below
about: true
blog: true

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com
